FROM node:18

# Defina o diretório de trabalho dentro do container
WORKDIR /app

# Copie os arquivos de dependências (package.json e package-lock.json)
COPY package*.json ./

# Instale as dependências do projeto
RUN npm install

# Copie todo o código-fonte da aplicação para o container
COPY . .

# Exponha a porta 3000
EXPOSE 3000

# Defina o comando para rodar o Next.js em modo de desenvolvimento
CMD ["npm", "run", "dev"]